# Generated by Django 3.2.6 on 2021-08-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work_experience',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
