# Generated by Django 3.2.6 on 2021-09-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0003_recent_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recent_projects',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Recent_Projects'},
        ),
    ]
